### PR TITLE
Place GraphQL and networking modules behind feature flags for speedy dev compilation

### PR DESCRIPTION
**Pull request by sandreae**
## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header

### CODE REVIEW

**Comment by adzialocha** [comment]
Hui! Is it getting too slow? How long are your compilation times?

I would move the features into the default feature set as we probably always want them, still one can opt out by setting the default feature flag to false.

**Comment by sandreae** [comment]
> I would move the features into the default feature set as we probably always want them, still one can opt out by setting the default feature flag to false.

Yes, this is the plan.

**Comment by sandreae** [comment]
> Hui! Is it getting too slow? How long are your compilation times?

The thing that's taking a while for me is `cargo check`.

If I run:
`cargo clean`
`cargo check --all-features --profile=test`

I get:
`Finished test [unoptimized + debuginfo] target(s) in 5m 34s`

Interested to see what you get here on your super computer ;-p

**Comment by adzialocha** [comment]
I've closed this for now as I can't see any drastic regressions in complication time on my machines (including an old laptop). I like the feature flag idea though but that's maybe another PR?

**Pull request closed without merging**
