### PR TITLE
Perform "quick commit" in materializer service

### PR DESCRIPTION
**Pull request by sandreae**
Uses https://github.com/p2panda/p2panda/pull/485 to perform a quick commit on a document instead of materializing from scratch.

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header

### CODE REVIEW

**Comment by sandreae** [comment]
This PR is still open, and I'm actually nervous to merge it, cos I think it will hide any concurrency bugs even deeper 😅

**Comment by adzialocha** [comment]
> This PR is still open, and I'm actually nervous to merge it, cos I think it will hide any concurrency bugs even deeper 😅

Oooh interesting, did you observe new / more issues on that branch?

**Comment by sandreae** [comment]
> > This PR is still open, and I'm actually nervous to merge it, cos I think it will hide any concurrency bugs even deeper sweat_smile
> 
> Oooh interesting, did you observe new / more issues on that branch?

No new observations I'm afraid. Just the thought that by using "quick commits" to update documents without issuing reduce tasks, then we'd probably make reproducing any concurrency bugs even hard....

**Comment by adzialocha** [comment]
I think the errors I get are all happening before materialization (it's always about duplicate seq num, log id or some missing operation id hashes).

Let me run this branch a couple of times and see if I can tell a difference in the issues. Would be nice to merge this!

**Comment by adzialocha** [comment]
> I think the errors I get are all happening before materialization (it's always about duplicate seq num, log id or some missing operation id hashes).
> 
> Let me run this branch a couple of times and see if I can tell a difference in the issues. Would be nice to merge this!

Same bugs as in https://github.com/p2panda/aquadoggo/issues/270, so all good 😆

**Comment by sandreae** [comment]
> > I think the errors I get are all happening before materialization (it's always about duplicate seq num, log id or some missing operation id hashes).
> > Let me run this branch a couple of times and see if I can tell a difference in the issues. Would be nice to merge this!
> 
> Same bugs as in #270, so all good laughing

Well, that's good..... lolz...

**Comment by sandreae** [comment]
I'll get this ready for merging when I have time then :+1:

**Review by adzialocha — APPROVED** [review]

**Pull request merged**
